localhost              ansible_connection=local

[fedora]
# 148.113.201.167
charlie.orca-uaru.ts.net ansible_user=fedora

[archlinux]
ape-0.orca-uaru.ts.net ansible_user=arch
apex.orca-uaru.ts.net ansible_uesr=arch

[droplet]
ape-0.orca-uaru.ts.net ansible_user=arch

[homelab]
apex.orca-uaru.ts.net ansible_uesr=arch

[ovh]
# 148.113.201.167
charlie.orca-uaru.ts.net ansible_user=fedora
